// Generated by gencpp from file snake_control/GetJointTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef SNAKE_CONTROL_MESSAGE_GETJOINTTRAJECTORYREQUEST_H
#define SNAKE_CONTROL_MESSAGE_GETJOINTTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace snake_control
{
template <class ContainerAllocator>
struct GetJointTrajectoryRequest_
{
  typedef GetJointTrajectoryRequest_<ContainerAllocator> Type;

  GetJointTrajectoryRequest_()
    {
    }
  GetJointTrajectoryRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetJointTrajectoryRequest_

typedef ::snake_control::GetJointTrajectoryRequest_<std::allocator<void> > GetJointTrajectoryRequest;

typedef boost::shared_ptr< ::snake_control::GetJointTrajectoryRequest > GetJointTrajectoryRequestPtr;
typedef boost::shared_ptr< ::snake_control::GetJointTrajectoryRequest const> GetJointTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace snake_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snake_control/GetJointTrajectoryRequest";
  }

  static const char* value(const ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetJointTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::snake_control::GetJointTrajectoryRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SNAKE_CONTROL_MESSAGE_GETJOINTTRAJECTORYREQUEST_H
